export interface iDetalleFactura{
    Index:number;
    Codigo: string;
    Producto: string;
    Precio: number;
    PrecioCordoba: number;
    PrecioDolar: number;
    PorcDescuento: number;
    PorcImpuesto: number;
    Cantidad: number;
    SubTotal:number;
    SubTotalCordoba:number;
    SubTotalDolar:number;
    Descuento:number;
    DescuentoCordoba:number;
    DescuentoDolar:number;
    SubTotalNeto:number;
    SubTotalNetoCordoba:number;
    SubTotalNetoDolar:number;
    Impuesto:number;
    ImpuestoCordoba:number;
    ImpuestoDolar:number;
    ImpuestoExo:number;
    ImpuestoExoCordoba:number;
    ImpuestoExoDolar:number;
    TotalCordoba:number;
    TotalDolar:number;
    EsBonif : boolean;
    EsExonerado : boolean;
    IndexUnion : number;
}