export interface iFactPed{
    IdVenta: string;
    TipoDocumento : string;
    Serie : string;
    NoFactura: string;
    NoPedido: string;
    CodCliente : string;
    NomCliente : string;
    Nombre : string;
    RucCedula: string;
    Contanto: string;
    Limite: number;
    Disponible: number;
    CodBodega: string;
    NomBodega: string;
    CodVendedor: string;
    NomVendedor: string;
    EsContraentrega: boolean;
    EsExportacion: boolean;
    OrdenCompra: string;
    Fecha: Date;
    Plazo: number;
    Vence: Date;
    Moneda:string;
    TipoVenta: string;
    TipoImpuesto: string;
    TipoExoneracion: string;
    NoExoneracion: string;
    EsDelivery: boolean;
    Direccion: string;
    Observaciones:string;
    Impuesto: number;
    Exonerado:number;
    TotalCordoba:number;
    TotalDolar:number;
    TasaCambio:number;
    PedirAutorizacion: boolean;
    FechaRegistro : Date;
    UsuarioRegistra : string;
    Estado : string;
    VentaDetalle : any[];
}